[package]
name = "ai-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
ai = { path = "../ai" }
tokio = { version = "1", features = ["full"] }
log = "0.4"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.11"
chrono = "0.4"
